apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-mysql-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard-rwo


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: andredeabreugoncalves/db-projeto:1.1
        args: 
        - "--ignore-db-dir=lost+found"
        imagePullPolicy: Always
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql

        volumeMounts:
        - name: data-mysql-db
          mountPath: /var/lib/mysql
      volumes:
      - name: data-mysql-db
        persistentVolumeClaim:
          claimName: data-mysql-db

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
spec:
  replicas: 6
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: andredeabreugoncalves/php-projeto:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80


